apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: knativeeventingsources.knative.dev
spec:
  group: knative.dev
  names:
    kind: KnativeEventingSources
    listKind: KnativeEventingSourcesList
    plural: knativeeventingsources
    singular: knativeeventingsources
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
